added join and create cards in separate files
LemonFace0309/Study-Space pull request #53
Opened 2021-06-15 22:58 UTC by mabelene

2021-06-16 06:12 UTC, LemonFace0309 requested changes
Great job overall!

2021-06-16 06:12 UTC, LemonFace0309 commented on components/Cards/CreateCard.js
> +}
did eslint not give you an error for not having an extra line at the end? You turned it on right :3

2021-06-16 06:12 UTC, LemonFace0309 commented on components/Container.js
> +        />
These cards are nearly identical. Can you abstract it into one? You can probably add a background prop (ex `light` or `dark`) and conditionally change it in `makeStyles`

2021-06-20 04:27 UTC, LemonFace0309 requested changes
After you changed the file structure the build stopped working. Make sure all your file imports are valid. You can test that by running `npm run build` in the console and checking that everything goes through.

2021-06-22 13:02 UTC, eden-chan commented
Not sure how to resolve this.
` npm run build

> ui1@0.1.0 build
> next build

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
info  - Creating an optimized production build  
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve '@material-ui/core/Alert' in '/home/eden/Repo/Study-Space/node_modules/@material-ui/lab/Alert'


> Build error occurred
Error: > Build failed because of webpack errors
    at /home/eden/Repo/Study-Space/node_modules/next/dist/build/index.js:15:918
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /home/eden/Repo/Study-Space/node_modules/next/dist/build/tracer.js:1:525`

2021-06-22 15:23 UTC, LemonFace0309 commented
> Not sure how to resolve this.
> ` npm run build
> 
> > ui1@0.1.0 build
> > next build
> 
> Browserslist: caniuse-lite is outdated. Please run:
> npx browserslist@latest --update-db
> info - Creating an optimized production build
> Failed to compile.
> 
> ModuleNotFoundError: Module not found: Error: Can't resolve '@material-ui/core/Alert' in '/home/eden/Repo/Study-Space/node_modules/@material-ui/lab/Alert'
> 
> > Build error occurred
> > Error: > Build failed because of webpack errors
> > at /home/eden/Repo/Study-Space/node_modules/next/dist/build/index.js:15:918
> > at runMicrotasks ()
> > at processTicksAndRejections (internal/process/task_queues.js:95:5)
> > at async /home/eden/Repo/Study-Space/node_modules/next/dist/build/tracer.js:1:525`

Are you using the Alert component? I think it's exported from `@material-ui/lab` or something like that and not `core`. You probably need to adjust imports to match. https://material-ui.com/components/alert/

2021-06-22 19:32 UTC, LemonFace0309 commented
@eden-chan @mabelene I fixed the deployment. Please merge the create/join spaces card into one now please. Msg me for clarity if you need it.

2021-06-22 20:09 UTC, LemonFace0309 requested changes

2021-06-22 20:09 UTC, LemonFace0309 commented on components/Dashboard/Cards/JoinCard.js
> +import React from "react";
Please delete if we're not gonna use it.

2021-06-22 20:09 UTC, LemonFace0309 commented on components/Dashboard/Cards/DashboardCard.js
> +}
missing new line

2021-06-22 20:38 UTC, LemonFace0309 commented on components/Dashboard/Cards/DashboardCard.js
> +}
make sure you have eslint on. It should've asked you to add PropTypes. It's not added here tho

2021-06-25 05:42 UTC, LemonFace0309 approved these changes

2021-06-25 05:42 UTC, merged