Draft: Feature/46/create dashboard charts
LemonFace0309/Study-Space pull request #69
Opened 2021-06-20 16:08 UTC by eden-chan

2021-06-21 02:28 UTC, LemonFace0309 requested changes
I noticed you have merge conflicts. This is probably because you branched off of your old branch instead of main. You might want to run `git rebase --onto main <old_branch_name_whatever_it_was>` and fix whatever merge conflcits you have locally before your next push to repo. Other than that, ping me once this branch is ready to be merged and not just a draft.

2021-06-24 05:40 UTC, LemonFace0309 commented
@eden-chan you can continue pushing changes into this branch before I approve, instead of creating a new branch that has the commit history of this one.

2021-06-24 05:42 UTC, LemonFace0309 commented
@eden-chan please make sure you resolve merge conflicts asap as well, instead of leaving it for the reviewer. 
![image](https://user-images.githubusercontent.com/65472533/123208536-4cdd9780-d48d-11eb-86e3-e0d97adf2426.png)

In this case, I think you have this because you either didn't branch off of main, or when you did, your main branch was a few commits behind the remote one. I will resolve it this time but please keep this in mind.

2021-06-24 05:52 UTC, LemonFace0309 commented
@eden-chan after quickly scanning through your branch, it looks like you still have remnants of your tailwind css experiments. Please clean this up and use eslint to make sure code is consistent.

2021-06-24 05:52 UTC, LemonFace0309 requested changes

2021-06-24 05:52 UTC, LemonFace0309 commented on components/Shared/Card.js
> +
why so spaced out?

2021-06-25 04:02 UTC, LemonFace0309 commented
Also, when doing `npm i` we get this error: `npm WARN deprecated @reactchartjs/react-chart.js@1.0.0-rc.4: This package is deprecated. Please switch to 'react-chartjs-2'`

@eden-chan do you think you can quickly update the package and adjust imports to fix this error?

2021-06-26 05:53 UTC, jimmyygit reviewed
rock solid ![image](https://user-images.githubusercontent.com/68363001/123503374-a6c29680-d620-11eb-92cb-dec671948f7c.png)

addressing the responsive part, I think just adding the grid props should do
https://material-ui.com/components/grid/#basic-grid

sorry if i commented on parts u didnt write, I dont know if the commits were mumbo jumbo so I just looked at everything

2021-06-26 05:53 UTC, jimmyygit commented on components/Dashboard/DashboardContainer.js
> +            <Grid item xs={6} container direction="column" spacing={3}>
I think this is the culprit for poor responsiveness. We are using `Grid` but were not taking full advantage of the flexibility it offers. Particularly with the "column width" props ie `xs` , `sm`, `md`. 
Web grid columns contain 12 fractions. We usually want adjacent grids to sum to 12. Common design pattern would be `xs={12} md={6}` which basically means "this grid col should be full width on x-small to medium and half width on medium and up"

![image](https://user-images.githubusercontent.com/68363001/123503170-454df800-d61f-11eb-93bb-93522ee42b30.png)

2021-06-26 05:53 UTC, jimmyygit commented on pages/dashboard/index.js
> +          <Grid item>
I think the nesting here is a bit redundant. One grid should do :)

2021-06-26 05:53 UTC, jimmyygit commented on pages/spaces/study-space-demo.js
> +            <Grid className="grid grid-cols-6 ml-5 space-x-5 space-y-5 ">
I think for the sake of consistency, we should define column widths in the props instead of classNames

2021-06-26 08:01 UTC, LemonFace0309 approved these changes

2021-06-26 22:00 UTC, merged