10x speed of this repo with 10x rocket ships
LemonFace0309/Study-Space pull request #92
Opened 2021-07-13 00:53 UTC by OrenLeung

🚀🚀🚀🚀

2021-07-13 00:54 UTC, OrenLeung commented
@LemonFace0309 @eden-chan @jimmyygit plz approval my critical PR

2021-07-13 01:38 UTC, jimmyygit requested changes
Not impressed.

2021-07-13 01:38 UTC, jimmyygit commented on README.md
> +# Getting Started 🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀
There are 16x rocket ships here. That is 6x too many according to the title.

2021-07-13 02:07 UTC, OrenLeung commented
resolved @jimmyygit suggestions and edited the PR title

2021-07-13 05:12 UTC, mabelene commented on README.md
> +# Getting Started 🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀
LOL what is happening

2021-07-13 08:13 UTC, LemonFace0309 requested changes
you can do better than just 16x...

2021-07-13 16:00 UTC, eden-chan approved these changes
LGTM!

2021-07-13 16:03 UTC, OrenLeung commented
@jimmyygit is @LemonFace0309's jeff dean 

[who could be yr 1000x engineer?](https://www.theengineeringmanager.com/growth/who-could-be-your-jeff-dean/)

2021-07-14 01:13 UTC, OrenLeung commented on README.md
> +# Getting Started 🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀
@mabelene plz approve and merge "LGTM"

2021-07-14 03:42 UTC, mabelene approved these changes
vercel doesn't work but other than that LGTM loll

2021-07-15 00:41 UTC, jimmyygit approved these changes

2021-08-24 04:59 UTC, LemonFace0309 approved these changes
We got 22 rocket ships instead of 16. @OrenLeung you're overachieving is respectable.

2021-08-24 05:00 UTC, merged